# RT-Thread building script for JerryScript RT port

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('ZephyrBlePort', src, depend = [''], CPPPATH = CPPPATH)
# depend = ['PKG_USING_ZEPHYRBLEPORT'], 

Return('group')
